name: "Hello world workflow"

# Controls when the workflow will run.
on:
  workflow_dispatch:

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - name: "Print Hello World"
        run: echo "Hello World !!!!"

      - name: "Print current date"
        run: date